### ISSUE TITLE
Please bump golang to 1.14

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/windows-tools-release#27]
Thank you!

**Comment by aemengo** [comment]
We appreciate you bringing this to our attention. We've shipped [v67](https://github.com/cloudfoundry/windows-tools-release/releases/tag/v67), which has the golang version systematically bumped in the job `golang-1-windows`. We've also removed the non-floating `golang-1.13-windows`, so that we'll have fewer of these out of date issue.

Thank you.
